# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_route', models.CharField(blank=True, db_index=True, max_length=50)),
                ('method', models.CharField(blank=True, db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('resource_url', models.URLField(blank=True)),
                ('example_request', models.TextField(blank=True)),
                ('example_response', models.TextField(blank=True)),
                ('response_format', models.CharField(blank=True, max_length=50)),
                ('authentication_required', models.NullBooleanField()),
                ('rate_limited', models.NullBooleanField()),
                ('limit_user', models.IntegerField(blank=True)),
                ('limit_app', models.IntegerField(blank=True)),
                ('parameters', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=50)),
                ('data_type', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(db_index=True, max_length=200, unique=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='apidoc',
            name='article',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.Article'),
        ),
    ]
