# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20171127_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidoc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apidoc',
            name='example_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apidoc',
            name='example_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apidoc',
            name='limit_app',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apidoc',
            name='limit_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apidoc',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apidoc',
            name='resource_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apidoc',
            name='response_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
