# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20171127_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('topic', 'data_type', 'title')]),
        ),
    ]
