# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20171127_0605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apidoc',
            unique_together=set([('api_route', 'method')]),
        ),
    ]
