# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_auto_20171127_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidoc',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='apidoc',
            unique_together=set([('api_route', 'method', 'title')]),
        ),
    ]
