# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_auto_20171127_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidoc',
            name='api_route',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
